### ISSUE TITLE
Pivots and helpers.getSignals()

### ISSUE THREAD

**Issue by chinmayrane** [anfederico/Gemini#1]
1. Is pivots a python package you are using through Pip?
2. The Readme has helpers.getSignals() from helper function while there is no such function in helper.py file.

**Comment by anfederico** [comment]
Ah sorry, that's confusing. No pivots is just a local library for some custom signals I use. This package doesn't come with any signals. The helpers.getSignals() is just supposed to be a placeholder for your own function that creates signals from your data.

**Comment by Kosteg** [comment]
Could you please provide .getSignals() example?

**Comment by tienduccao** [comment]
An example of `.getSignals()` is really helpful

**Comment by anfederico** [comment]
I will add a real example soon.

**Comment by chenopan** [comment]
Still waiting for example of `getSignals()`. Thx )

**Comment by iamraa** [comment]
Refactored backtester with examples: https://github.com/friendly-pig/gemini.backtester

**Comment by kweitzner** [comment]
Can you show an example of what .getSignals() would look like?  It's not obvious how to set this function up.  Doesn't look like the fork Alexander set up uses this function.
