### ISSUE TITLE
No lines inside chart.html

### ISSUE THREAD

**Issue by 11** [anfederico/gemini#28]
### User Info
Google Chrome: 87.0.4280.88 (Official Build) (x86_64)
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | macOS Version 10.15.7 (Build 19H2)
JavaScript | V8 8.7.220.29
Flash | 32.0.0.465 /Users/douglasrudolph/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.465/PepperFlashPlayer.plugin

### Description
No lines were rendered inside `chart.html` after running  `backtest.chart()` on your example backtest algorithm and `BTCUSD` data

<b>Here's a screenshot of the chart:</b>
![image](https://user-images.githubusercontent.com/6809522/102444827-157ec180-3ff8-11eb-892d-af9af204a23a.png)

<b>This was the guide I was following:</b>
https://gemini-docs.readthedocs.io/en/latest/using-gemini.html#basic

<b>This was the data I used:</b>
https://github.com/anfederico/gemini/blob/master/examples/data/BTC_USD.csv

<b>This is the HTML that was generated into chart.html:</b>
https://gist.github.com/11/159820cdf0a7b8dd69bd928add991acd

### Cheers 🍻
PS: Thanks for the amazing API -- loving everything about this project

**Comment by 11** [comment]
Update -- I was able to fix this issue. Here is the PR if you would like to merge it @anfederico  https://github.com/anfederico/gemini/pull/29

**Comment by anfederico** [comment]
This should be resolved in the latest update.
