### ISSUE TITLE
Keep getting error when I ran the reversion example

### ISSUE THREAD

**Issue by drxav13r** [anfederico/gemini#31]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-eccef78b8d96> in <module>
----> 1 output = backtest.start(100000, logic)

~/opt/anaconda3/lib/python3.8/site-packages/gemini/gemini_core/engine.py in start(self, initial_capital, logic)
     41         """
     42         self.tracker = []
---> 43         self.account = exchange.account(initial_capital)
     44 
     45         # Enter backtest ---------------------------------------------

AttributeError: module 'gemini_core.exchange' has no attribute 'account'

**Comment by drxav13r** [comment]
That is from the output = backtest.start(100000, logic)

**Comment by DanLeePy** [comment]
Hi @drxav13r ,

I had the same issue as you, I believe there is some discrepancy in how the Account class is instantiated.
It should be exchange.Account instead.

[](https://github.com/anfederico/gemini/pull/32/files)

You can refer to my PR, where I made a few changes to be able to run this code.

Once again, thanks @anfederico for this brilliant library!

**Comment by anfederico** [comment]
Good fix - merged.
