### ISSUE TITLE
Will you continue updating this project

### ISSUE THREAD

**Issue by ramoslin02** [anfederico/Gemini#6]
Hi, We see that your project did not update for a long time , will you update the project and add some new features for this project ?

**Comment by anfederico** [comment]
For now I don't have any immediate plans to update this project. I've been planning to add a real dataset as well as an effective mean reversion strategy, but I've been to busy lately.

**Comment by ramoslin02** [comment]
Ok, hope you update the project more quickly, I did not find any good backtesting project for cryptocurrency. So this project is very good.

**Comment by anfederico** [comment]
It should work as is, it just doesn't provide any default strategies.
